server:
  port: 9002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop?socketTimeout=90
    username: joe.zhang
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 0
      connection-timeout: 50000
    driver-class-name: org.postgresql.Driver